required_devices: 8
resume: false

no_test: false
test_only: false
debug: false
seed: 0
distributed: false
test_freq: 5
num_workers: 20

benchmark:
  name: "ucf101-full_finetune_112X112x32"

dataset:
  name: "ucf101"
  overfit_tiny: false
  overfit_samples: 1000
  overfit_seed: 0
  fold: 1
  batch_size: 12
  clip_duration: 1.0
  video_fps: 16.
  crop_size: 112
  transform: "msc+color"
  min_area: 0.08
  color: [0.4, 0.4, 0.4, 0.2]
  train:
    split: "trainlist{fold:02d}"
    mode: "clip"
    clips_per_video: 1
    use_augmentation: false
    use_shuffle: true
    drop_last: true
  test:
    split: "testlist{fold:02d}"
    mode: "clip"
    clips_per_video: 1
    use_augmentation: false
    use_shuffle: false
    drop_last: false
  test_dense:
    split: "testlist{fold:02d}"
    mode: "video"
    clips_per_video: 10
    use_augmentation: false
    use_shuffle: false
    drop_last: false

optimizer:
  name: "adam"
  num_epochs: 20
  weight_decay: 0.0
  warmup_classifier: false
  lr:
    name: "multistep"
    base_lr: 0.00001
    gamma: 1.0
    milestones: [6, 10, 13]

model:
  args:
    n_classes: 2
    feat_dim: 512
