required_devices: 8
resume: false

no_test: false
test_only: false
debug: false
seed: 0
distributed: false
test_freq: 5
num_workers: 20

benchmark:
  name: "ucf101-video_retrieval_112X112x32"

dataset:
  name: "ucf101"
  fold: 1
  batch_size: 64
  clip_duration: 1.0
  video_fps: 16.
  crop_size: 112
  resize: 128
  video_fps: 16.
  transform: "msc+color"
  min_area: 0.08
  color: [0.4, 0.4, 0.4, 0.2]
  train:
    split: "trainlist{fold:02d}"
    clips_per_video: 10
    mode: "video"
    use_augmentation: false # no augmentations during train as well
    use_shuffle: false
    drop_last: false
  test:
    split: "testlist{fold:02d}"
    clips_per_video: 10
    mode: "video"
    use_augmentation: false
    use_shuffle: false
    drop_last: false
  test_dense:
    split: "testlist{fold:02d}"
    mode: "video"
    clips_per_video: 10
    use_augmentation: false
    use_shuffle: false
    drop_last: false

optimizer:
  name: "adam"
  num_epochs: 10
  weight_decay: 0.0
  warmup_classifier: false
  lr:
    name: "multistep"
    base_lr: 0.0001
    gamma: 1.0
    milestones: [5, 8]

model:
  args:
    n_classes: 2
    feat_dim: 512
