
required_devices: 8
resume: false

no_test: false
test_only: false
debug: false
seed: 0
distributed: false
test_freq: 5
num_workers: 5

benchmark:
  name: "ucf101-model_compare_112X112x32"

dataset:
  name: "ucf101"
  fold: 1
  batch_size: 5
  clip_duration: 1.0
  video_fps: 16.
  crop_size: 112
  resize: 128
  transform: "crop+color"
  color: [0., 0., 0., 0.]
  switch_channels: false
  normalize: true
  train:
    split: "trainlist{fold:02d}"
    mode: "clip"
    clips_per_video: 10
    use_augmentation: false
    use_shuffle: false
    drop_last: true
  test:
    split: "testlist{fold:02d}"
    mode: "clip"
    clips_per_video: 5
    use_augmentation: false
    use_shuffle: false
    drop_last: true
  test_dense:
    split: "testlist{fold:02d}"
    mode: "video"
    clips_per_video: 10
    use_augmentation: false
    use_shuffle: false
    drop_last: false

optimizer:
  name: "adam"
  num_epochs: 10
  weight_decay: 0.0
  warmup_classifier: false
  lr:
    name: "multistep"
    base_lr: 0.01
    gamma: 0.3
    milestones: [4, 8, 10]

model:
  args:
    n_classes: 101
    feat_dim: 512
